<?php
namespace App\Controller;
use Cake\ORM\TableRegistry;
use Cake\Datasource\ConnectionManager;


class AllsortersController extends AppController
{


    public function isAuthorized($user)
    {
        // return $user['id'] > 0;
        return $this->Auth->user('role') > 2;
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow(['home', 'homepage']);
//        $this->viewBuilder()->setLayout('client');
        $this->loadModel('Webpages');
        $this->loadModel('Service');
        $this->loadModel('BlogPost');
        $this->loadModel('Review');
        $this->loadModel('slideshow');
        $this->loadModel('gallery_page');
        $this->loadModel('Image');
        $this->loadComponent('Paginator');

    }

    public function home()
    {
        $this->viewBuilder()->setLayout('client_default');

        $this->paginate = ['limit'=>3];
        $services = $this->Service->find('all');
        $this->set('services', $this->paginate($services));

        $reviews = $this->Review->find('all');
        $this->set('reviews', $this->paginate($reviews));

        $blogs = $this->BlogPost->find('all')->order(['created' => 'DESC']);
        $this->paginate = ['limit'=>3];
        $this->set('blogs', $this->paginate($blogs));

        $connection = ConnectionManager::get('default');
        $slideshow = $connection->execute('SELECT * FROM slideshow join image on image.Image_id = slideshow.Image_id ORDER BY image.name LIMIT 4')->fetchAll('assoc');
        $this->set('slideshow', $slideshow);

        $slideshow_arr = $this->slideshow->find('all');
        $this->set('slideshow_arr', $slideshow_arr);

        $gallery_images = $this->Image->find('all')->where(['Shown' => true]);
        $this->set(compact('gallery_images'));

        $images = $this->Image->find('all');
        $this->set(compact('images'));


        $webpages = $this->Webpages->find('all');
        $this->set(compact('webpages'));
        $this->set('title', 'Home of AllSorters');
    }

}
