<?php
namespace App\Controller;
use Cake\ORM\TableRegistry;
use Cake\Datasource\ConnectionManager;


class ArticlesController extends AppController
{


    public function isAuthorized($user)
    {
        // return $user['id'] > 0;
        return $this->Auth->user('role') > 2;
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow(['home', 'homepage']);
//        $this->viewBuilder()->setLayout('client');
        $this->loadModel('Webpages');

    }

    public function home()
    {
        $this->viewBuilder()->setLayout('client');

        $connection = ConnectionManager::get('default');
        $services = $connection->execute('SELECT DISTINCT * FROM service join service_image on service.Service_id = service_image.Service_id join image on service_image.Image_id = image.Image_id GROUP BY service.Service_id LIMIT 6')->fetchAll('assoc');
        $this->set('services', $services);

        $slideshow = $connection->execute('SELECT * FROM slideshow join image on image.Image_id = slideshow.Image_id ORDER BY image.name LIMIT 4')->fetchAll('assoc');
        $this->set('slideshow', $slideshow);


        $blogs = $connection->execute('Select * from blog_post LIMIT 5') ->fetchAll('assoc');
        $this->set('blogs', $blogs);

        $webpages = $this->Webpages->find('all');
        $this->set(compact('webpages'));


        // This view doesn't actually need to load any data to pass to the view,
        // because it is all hardcoded in the src/Templates/Articles/home.ctp template.
    }
    public function homepage() {
        $this->viewBuilder()->setLayout('client_default');
    }

}
